#!/usr/bin/env python3
"""GitHub Action entrypoint for AI Counsel code review.

Runs a deliberation panel on a PR diff and outputs structured results.
"""
import argparse
import asyncio
import json
import sys
from pathlib import Path


async def run_review(args):
    """Run the code review deliberation."""
    from models.config import load_config
    from adapters import create_adapter
    from deliberation.engine import DeliberationEngine
    from models.schema import DeliberateRequest, Participant

    # Load config
    config_path = Path(__file__).parent / "config.yaml"
    config = load_config(str(config_path))

    # Load panels
    import yaml
    panels_path = Path(__file__).parent / "panels.yaml"
    with open(panels_path) as f:
        panels_data = yaml.safe_load(f)
    panels = panels_data.get("panels", {})

    if args.panel not in panels:
        print(f"ERROR: Unknown panel '{args.panel}'. Available: {', '.join(panels.keys())}")
        sys.exit(1)

    panel = panels[args.panel]

    # Read diff file as context
    diff_context = ""
    if args.diff_file and Path(args.diff_file).exists():
        diff_text = Path(args.diff_file).read_text(errors="replace")
        # Truncate if very large (>50KB)
        if len(diff_text) > 50000:
            diff_text = diff_text[:50000] + "\n\n[...diff truncated at 50KB...]"
        diff_context = f"## Code Diff to Review\n\n```diff\n{diff_text}\n```"

    # Build adapters
    adapters = {}
    if config.cli_tools:
        for name, tool_config in config.cli_tools.items():
            try:
                adapters[name] = create_adapter(name, tool_config)
            except Exception:
                pass
    if config.adapters:
        for name, adapter_config in config.adapters.items():
            try:
                adapters[name] = create_adapter(name, adapter_config)
            except Exception:
                pass

    # Build engine
    engine = DeliberationEngine(adapters, config=config, server_dir=Path(__file__).parent)

    # Build request
    question = "Review the following code changes for quality, security, and correctness issues."
    if diff_context:
        question = f"{question}\n\n{diff_context}"

    request = DeliberateRequest(
        question=question,
        participants=[Participant(**p) for p in panel["participants"]],
        rounds=int(args.rounds),
        mode=panel.get("mode", "quick"),
        working_directory=args.working_directory,
    )

    # Execute
    result = await engine.execute(request)

    # Build output
    output = {
        "verdict": "NEEDS_DISCUSSION",
        "findings_count": 0,
        "risk_level": "unknown",
        "summary": result.summary.consensus if result.summary else "No summary",
        "executive_summary": result.summary.executive_summary if result.summary else None,
    }

    if result.structured_findings:
        sf = result.structured_findings
        output["verdict"] = sf.verdict
        output["findings_count"] = len(sf.findings)
        output["risk_level"] = sf.risk_level
        output["findings"] = [f.model_dump() for f in sf.findings]

    # Write JSON output
    if args.output_file:
        with open(args.output_file, "w") as f:
            json.dump(output, f, indent=2, default=str)

    # Write markdown report for PR comment
    report_path = Path(args.output_file).parent / "review_report.md" if args.output_file else Path("/tmp/review_report.md")
    report_lines = [
        "## AI Counsel Code Review",
        "",
        f"**Verdict:** {output['verdict']} | **Risk Level:** {output['risk_level']} | **Findings:** {output['findings_count']}",
        "",
    ]

    if output.get("executive_summary"):
        report_lines.extend(["### Summary", "", output["executive_summary"], ""])

    if result.structured_findings and result.structured_findings.findings:
        report_lines.extend(["### Findings", "", "| # | Severity | Category | Description |", "|---|----------|----------|-------------|"])
        for i, f in enumerate(result.structured_findings.findings, 1):
            report_lines.append(f"| {i} | {f.severity} | {f.category} | {f.description} |")
        report_lines.append("")

    report_lines.append("---")
    report_lines.append("*Generated by [AI Counsel](https://github.com/loftsshuki/ai-counsel)*")

    with open(report_path, "w") as f:
        f.write("\n".join(report_lines))

    # Print summary
    print(f"Verdict: {output['verdict']}")
    print(f"Risk Level: {output['risk_level']}")
    print(f"Findings: {output['findings_count']}")

    # Fail if critical findings and fail_on_critical is set
    if args.fail_on_critical == "true" and result.structured_findings:
        critical = [f for f in result.structured_findings.findings if f.severity == "critical"]
        if critical:
            print(f"\nFAILED: {len(critical)} critical finding(s) detected")
            sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="AI Counsel GitHub Action entrypoint")
    parser.add_argument("--panel", default="pre-commit-review")
    parser.add_argument("--working-directory", default=".")
    parser.add_argument("--rounds", default="2")
    parser.add_argument("--diff-file", default=None)
    parser.add_argument("--output-file", default="/tmp/review_result.json")
    parser.add_argument("--fail-on-critical", default="true")

    args = parser.parse_args()
    asyncio.run(run_review(args))


if __name__ == "__main__":
    main()
